cmake_minimum_required(VERSION 3.4)
project(print)
option(BUILD_TESTS "Build tests" OFF)
add_library(print STATIC sources/print.cpp)
target_include_directories(print PUBLIC include)
if(BUILD_TESTS)
  enable_testing()
  add_executable(check tests/test1.cpp)
  target_include_directories(check PRIVATE include third-party/gtest/include)
  target_link_libraries(check print)
  add_test(NAME check COMMAND check)
endif()
